### PR TITLE
Pass ldflags to each command's context

### LINKED ISSUE #62: -ldflags doesn't work in v2
Since v2 of fyne-cross, the `-ldflags` command line option is not passed to Docker anymore:

```
$ fyne-cross linux -debug -ldflags "-X main.version=1.2.3"
[i] Target: linux/amd64
command.Context{Volume:volume.Volume{binDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/bin", cacheDirHost:"/home/alexis/.cache/fyne-cross", distDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/dist", tmpDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/tmp", workDirHost:"/home/alexis/fyne-cross-ldflags"}, Architecture:"amd64", Env:[]string{"GOOS=linux", "GOARCH=amd64", "CC=gcc"}, ID:"linux-amd64", LdFlags:[]string(nil), OS:"linux", Tags:[]string(nil), AppID:"fyne-cross-ldflags", CacheEnabled:true, DockerImage:"lucor/fyne-cross:base-latest", Icon:"/home/alexis/fyne-cross-ldflags/Icon.png", Output:"fyne-cross-ldflags", Package:".", StripDebug:true, Debug:true}
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/bin/linux-amd64
[✓] "dist" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/dist/linux-amd64
[✓] "temp" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/tmp/linux-amd64
[i] Checking for go.mod: /home/alexis/fyne-cross-ldflags/go.mod
[✓] go.mod found
[i] Building binary...
/usr/bin/docker run --rm -t -w /app -v /home/alexis/fyne-cross-ldflags:/app -v /home/alexis/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e GOOS=linux -e GOARCH=amd64 -e CC=gcc -e fyne_uid=1000 lucor/fyne-cross:base-latest go build -ldflags '-w -s' -o /app/fyne-cross/bin/linux-amd64/fyne-cross-ldflags -v .
[✓] Binary: /home/alexis/fyne-cross-ldflags/fyne-cross/bin/linux-amd64/fyne-cross-ldflags
[i] Packaging app...
/usr/bin/docker run --rm -t -w /app/fyne-cross/tmp/linux-amd64 -v /home/alexis/fyne-cross-ldflags:/app -v /home/alexis/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e fyne_uid=1000 lucor/fyne-cross:base-latest /usr/local/bin/fyne package -os linux -name fyne-cross-ldflags -icon /app/fyne-cross/tmp/linux-amd64/Icon.png -appID fyne-cross-ldflags -executable /app/fyne-cross/bin/linux-amd64/fyne-cross-ldflags
[✓] Package: /home/alexis/fyne-cross-ldflags/fyne-cross/dist/linux-amd64/fyne-cross-ldflags.tar.gz
```

Here's the sample program I used to test:

```go
package main

import (
	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
)

var version string

func main() {
	a := app.New()

	w := a.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel(version),
		widget.NewButton("Quit", func() {
			a.Quit()
		}),
	))

	w.ShowAndRun()
}
```

With `go build -ldflags="-s -w -X main.version=1.2.3"`, we can see the version number in the label, but the label is empty when building with `fyne-cross linux -ldflags "-X main.version=1.2.3"`

### PR DESCRIPTION
**Pull request by jeandeaual**
Fixes #62 

`flags.Ldflags` was not passed to the context of each command.

Now, with no ldflags, building on Linux, only `-s -w` is set:

```
$ fyne-cross linux -debug
[i] Target: linux/amd64
command.Context{Volume:volume.Volume{binDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/bin", cacheDirHost:"/home/alexis/.cache/fyne-cross", distDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/dist", tmpDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/tmp", workDirHost:"/home/alexis/fyne-cross-ldflags"}, Architecture:"amd64", Env:[]string{"GOOS=linux", "GOARCH=amd64", "CC=gcc"}, ID:"linux-amd64", LdFlags:[]string(nil), OS:"linux", Tags:[]string(nil), AppID:"fyne-cross-ldflags", CacheEnabled:true, DockerImage:"lucor/fyne-cross:base-latest", Icon:"/home/alexis/fyne-cross-ldflags/Icon.png", Output:"fyne-cross-ldflags", Package:".", StripDebug:true, Debug:true}
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/bin/linux-amd64
[✓] "dist" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/dist/linux-amd64
[✓] "temp" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/tmp/linux-amd64
[i] Checking for go.mod: /home/alexis/fyne-cross-ldflags/go.mod
[✓] go.mod found
[i] Building binary...
/usr/bin/docker run --rm -t -w /app -v /home/alexis/fyne-cross-ldflags:/app -v /home/alexis/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e GOOS=linux -e GOARCH=amd64 -e CC=gcc -e fyne_uid=1000 lucor/fyne-cross:base-latest go build -ldflags '-w -s' -o /app/fyne-cross/bin/linux-amd64/fyne-cross-ldflags -v .
[✓] Binary: /home/alexis/fyne-cross-ldflags/fyne-cross/bin/linux-amd64/fyne-cross-ldflags
[i] Packaging app...
/usr/bin/docker run --rm -t -w /app/fyne-cross/tmp/linux-amd64 -v /home/alexis/fyne-cross-ldflags:/app -v /home/alexis/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e fyne_uid=1000 lucor/fyne-cross:base-latest /usr/local/bin/fyne package -os linux -name fyne-cross-ldflags -icon /app/fyne-cross/tmp/linux-amd64/Icon.png -appID fyne-cross-ldflags -executable /app/fyne-cross/bin/linux-amd64/fyne-cross-ldflags
[✓] Package: /home/alexis/fyne-cross-ldflags/fyne-cross/dist/linux-amd64/fyne-cross-ldflags.tar.gz
```

When set, the ldflags are passed along `-s -w`:

```
$ fyne-cross linux -debug -ldflags "-X main.version=1.2.3"
[i] Target: linux/amd64
command.Context{Volume:volume.Volume{binDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/bin", cacheDirHost:"/home/alexis/.cache/fyne-cross", distDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/dist", tmpDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/tmp", workDirHost:"/home/alexis/fyne-cross-ldflags"}, Architecture:"amd64", Env:[]string{"GOOS=linux", "GOARCH=amd64", "CC=gcc"}, ID:"linux-amd64", LdFlags:[]string{"-X main.version=1.2.3"}, OS:"linux", Tags:[]string(nil), AppID:"fyne-cross-ldflags", CacheEnabled:true, DockerImage:"lucor/fyne-cross:base-latest", Icon:"/home/alexis/fyne-cross-ldflags/Icon.png", Output:"fyne-cross-ldflags", Package:".", StripDebug:true, Debug:true}
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/bin/linux-amd64
[✓] "dist" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/dist/linux-amd64
[✓] "temp" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/tmp/linux-amd64
[i] Checking for go.mod: /home/alexis/fyne-cross-ldflags/go.mod
[✓] go.mod found
[i] Building binary...
/usr/bin/docker run --rm -t -w /app -v /home/alexis/fyne-cross-ldflags:/app -v /home/alexis/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e GOOS=linux -e GOARCH=amd64 -e CC=gcc -e fyne_uid=1000 lucor/fyne-cross:base-latest go build -ldflags '-X main.version=1.2.3 -w -s' -o /app/fyne-cross/bin/linux-amd64/fyne-cross-ldflags -v .
[✓] Binary: /home/alexis/fyne-cross-ldflags/fyne-cross/bin/linux-amd64/fyne-cross-ldflags
[i] Packaging app...
/usr/bin/docker run --rm -t -w /app/fyne-cross/tmp/linux-amd64 -v /home/alexis/fyne-cross-ldflags:/app -v /home/alexis/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e fyne_uid=1000 lucor/fyne-cross:base-latest /usr/local/bin/fyne package -os linux -name fyne-cross-ldflags -icon /app/fyne-cross/tmp/linux-amd64/Icon.png -appID fyne-cross-ldflags -executable /app/fyne-cross/bin/linux-amd64/fyne-cross-ldflags
[✓] Package: /home/alexis/fyne-cross-ldflags/fyne-cross/dist/linux-amd64/fyne-cross-ldflags.tar.gz
```

On Windows, `-H windowsgui` is also passed if `-no-strip-debug` is not set:

```
$ fyne-cross windows -debug -ldflags "-X main.version=1.2.3"
[i] Target: windows/amd64
command.Context{Volume:volume.Volume{binDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/bin", cacheDirHost:"/home/alexis/.cache/fyne-cross", distDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/dist", tmpDirHost:"/home/alexis/fyne-cross-ldflags/fyne-cross/tmp", workDirHost:"/home/alexis/fyne-cross-ldflags"}, Architecture:"amd64", Env:[]string{"GOOS=windows", "GOARCH=amd64", "CC=x86_64-w64-mingw32-gcc"}, ID:"windows-amd64", LdFlags:[]string{"-X main.version=1.2.3", "-H windowsgui"}, OS:"windows", Tags:[]string(nil), AppID:"fyne-cross-ldflags", CacheEnabled:true, DockerImage:"lucor/fyne-cross:base-latest", Icon:"/home/alexis/fyne-cross-ldflags/Icon.png", Output:"fyne-cross-ldflags.exe", Package:".", StripDebug:true, Debug:true}
[i] Cleaning target directories...
[✓] "dist" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/dist/windows-amd64
[✓] "temp" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/tmp/windows-amd64
[✓] "bin" dir cleaned: /home/alexis/fyne-cross-ldflags/fyne-cross/bin/windows-amd64
[i] Checking for go.mod: /home/alexis/fyne-cross-ldflags/go.mod
[✓] go.mod found
/usr/bin/docker run --rm -t -w /app/fyne-cross/tmp/windows-amd64 -v /home/alexis/fyne-cross-ldflags:/app -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e fyne_uid=1000 lucor/fyne-cross:base-latest /usr/local/bin/gowindres -arch amd64 -output fyne-cross-ldflags.exe -workdir /app/fyne-cross/tmp/windows-amd64
[i] Building binary...
/usr/bin/docker run --rm -t -w /app -v /home/alexis/fyne-cross-ldflags:/app -v /home/alexis/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e GOOS=windows -e GOARCH=amd64 -e CC=x86_64-w64-mingw32-gcc -e fyne_uid=1000 lucor/fyne-cross:base-latest go build -ldflags '-X main.version=1.2.3 -H windowsgui -w -s' -o /app/fyne-cross/bin/windows-amd64/fyne-cross-ldflags.exe -v .
[✓] Binary: /home/alexis/fyne-cross-ldflags/fyne-cross/bin/windows-amd64/fyne-cross-ldflags.exe
[i] Packaging app...
[✓] Package: /home/alexis/fyne-cross-ldflags/fyne-cross/dist/windows-amd64/fyne-cross-ldflags.exe.zip
```

### CODE REVIEW

**Review by lucor — CHANGES_REQUESTED** [review]
@jeandeaual thanks for the catch!
The fix looks good to me. Just few minor things before merge... could you please update the PR to merge against the develop branch? Additionally it'd be great to have a test that cover this fix :)

**Comment by jeandeaual** [comment]
@lucor I updated the PR to merge against develop.
For the test, I'm not sure where to add it. Is it fine if I add a new `TestGoBuild` test function for `goBuild`?

**Comment by lucor** [comment]
what about adding a test that covers `makeWindowsContext` for the  `-H windowsgui` and one that covers `makeDefaultContext` ? 
We could move
```
if len(flags.Ldflags) > 0 {
	ctx.LdFlags = append(ctx.LdFlags, flags.Ldflags)
}
```

inside makeDefaultContext

**Comment by lucor** [comment]
For the structure something like:
- `windows_test.go` -> `func Test_makeWindowsContext(t *testing.T)`
- `context_test.go` -> `func Test_makeDefaultContext(t *testing.T)`

**Comment by jeandeaual** [comment]
@lucor I added tests for `makeWindowsContext` and `makeDefaultContext`, as requested.
I tried to follow the style of `docker_test.go`. Let me know what you think.

File: internal/command/context_test.go [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+func Test_makeDefaultContext(t *testing.T) {
+	type args struct {
+		flags *CommonFlags
+	}
+	tests := []struct {
+		name        string
+		args        args
+		wantEnv     []string
+		wantLdFlags []string
```
Comment (lucor) [inline internal/command/context_test.go:16]:
```suggestion
		want Context
		wantErr bool
```
what about testing directly the function output ?

**Review by lucor — CHANGES_REQUESTED** [review]
Added a small note about test

File: internal/command/context_test.go (hunk 1 above)
Comment (lucor) [reply internal/command/context_test.go:16]: Anyway the fix is covered and I'll have to add other test cases to this due to another bug so I'm going to merge as is ;)
Thanks!
